"""
nextflow_config.py  --  generate the nextflow.config for the head instance.

The config is rendered at runtime so we can inject:
  - queueSize  (derived from truffle quota query)
  - workDir    (s3://bucket/work/job-name/)
  - region     (from config.py)
  - AMI ID     (from config.py, pre-baked with the tools stack)
  - S3 bucket  (for progress trace file)
"""

from __future__ import annotations

# Variant-calling process labels → instance types, per architecture.
# The x86↔arm64 benchmark uses MATCHED PAIRS (identical vCPU/RAM, differ only in
# family): c7i↔c7g, r7i↔r7g. Never mix sizes — that would confound architecture
# with instance size. arm64 runs aarchbio native containers; x86 runs upstream
# amd64 biocontainers. Neither emulates.
# custom main.nf label→process mapping (CALL_VARIANTS/MERGE_VCFS/VCF_STATS):
#   process_single: VCF_STATS — bcftools stats on the merged VCF (light, one task)
#   process_medium: CALL_VARIANTS — the FAN-OUT stage; bcftools mpileup/call per
#                   sample, reads the shared reference from FSx
#   process_high:   MERGE_VCFS — bcftools merge (fan-in, one task)
#   process_low:    unused by any process (fallback only)
_LABEL_INSTANCE_TYPES_BY_ARCH: dict[str, dict[str, str]] = {
    "arm64": {
        "process_single": "c7g.large",  # VCF_STATS
        "process_low": "c7g.large",  # fallback; unused by any process
        "process_medium": "c7g.2xlarge",  # CALL_VARIANTS (per-sample fan-out)
        "process_high": "r7g.2xlarge",  # MERGE_VCFS
    },
    "x86": {
        "process_single": "c7i.large",  # matched pair of c7g.large
        "process_low": "c7i.large",
        "process_medium": "c7i.2xlarge",  # matched pair of c7g.2xlarge
        "process_high": "r7i.2xlarge",  # matched pair of r7g.2xlarge
    },
}


def _arch(cfg) -> str:
    """Benchmark architecture: 'arm64' (default) or 'x86'. Read from cfg.BENCH_ARCH."""
    a = getattr(cfg, "BENCH_ARCH", "arm64")
    if a not in ("arm64", "x86"):
        raise ValueError(f"BENCH_ARCH must be 'arm64' or 'x86', got {a!r}")
    return a


def all_instance_types(cfg) -> list[str]:
    """Instance types in use for the configured arch — for truffle quota + cost."""
    arch = _arch(cfg)
    labels = _LABEL_INSTANCE_TYPES_BY_ARCH[arch]
    return sorted(set(labels.values()))


# Back-compat module-level default (arm64) for callers that import these directly.
_LABEL_INSTANCE_TYPES: dict[str, str] = _LABEL_INSTANCE_TYPES_BY_ARCH["arm64"]
ALL_INSTANCE_TYPES: list[str] = sorted(set(_LABEL_INSTANCE_TYPES.values()))

_TEMPLATE = """\
// nextflow.config — generated by aws-omics-demo
// DO NOT EDIT: regenerated on each run with live quota data

plugins {{
    id 'nf-spawn@0.8.0'
    id 'nf-amazon@2.8.0'   // required for s3:// workDir support
}}

docker {{
    enabled = true
    runOptions = '--user root'
}}

process {{
    executor = 'spawn'

    // Each withLabel block must include ALL ext.* fields — Nextflow does not
    // merge the global ext with a label-specific ext block.
    withLabel: 'process_single' {{
        ext.instanceType = '{inst_single}'
        ext.region       = '{region}'
        {az_line}ext.ttl          = '2h'
        ext.ami          = '{ami_id_tools}'  // tools AMI: VCF_STATS (bcftools stats)
        ext.volumeSize   = {volume_size}
    }}
    withLabel: 'process_low' {{
        ext.instanceType = '{inst_low}'
        ext.region       = '{region}'
        {az_line}ext.ttl          = '2h'
        ext.ami          = '{ami_id_tools}'  // tools AMI fallback
        ext.volumeSize   = {volume_size}
    }}
    withLabel: 'process_medium' {{
        ext.instanceType = '{inst_medium}'
        ext.region       = '{region}'
        {az_line}ext.ttl          = '2h'
        ext.ami          = '{ami_id_tools}'  // tools AMI: CALL_VARIANTS (bcftools mpileup/call)
        // CALL_VARIANTS reads the low-coverage BAM straight from s3://1000genomes
        // and writes a small per-sample chr20 VCF; the BAM streams through, so the
        // root volume only needs working headroom. (Override: VOLUME_SIZE.)
        ext.volumeSize   = {volume_size}
        // Shared read-only human reference genome delivered here (FSx → EBS →
        // baked). The reference lives once at <mount>/reference; every parallel
        // CALL_VARIANTS task reads it in place. Empty when neither FSX_ID nor
        // REFERENCE_SNAPSHOT is set (falls back to the baked-AMI reference).
        {ref_delivery_line}
    }}
    withLabel: 'process_high' {{
        ext.instanceType = '{inst_high}'
        ext.region       = '{region}'
        {az_line}ext.ttl          = '2h'
        ext.ami          = '{ami_id_tools}'  // tools AMI: MERGE_VCFS (bcftools merge)
        ext.volumeSize   = {volume_size}
    }}
    // Fallback for unlabelled processes.
    ext.instanceType = '{inst_low}'
    ext.region       = '{region}'
    {az_line}ext.ttl          = '2h'
    ext.ami          = '{ami_id_tools}'  // tools AMI
    ext.volumeSize   = {volume_size}

    // Environment variables inherited by all nf-spawn task submissions.
    // HOME is required by the spawn CLI to locate its config directory.
    environment = [
        HOME:                       '/root',
        AWS_DEFAULT_REGION:         '{region}',
        AWS_REGION:                 '{region}',
        AWS_STS_REGIONAL_ENDPOINTS: 'regional',
    ]
}}

executor {{
    name      = 'spawn'
    queueSize = {queue_size}    // derived from truffle quota query
}}

params {{
    // Custom variant-calling pipeline (main.nf) inputs.
    // samples    : CSV of sample_id,population,super_population,bam_path — one row
    //              per 1000 Genomes sample; CALL_VARIANTS fans out over the rows.
    // reference  : the shared human reference genome (s3:// marker — staged
    //              zero-copy off the FSx/EBS mount via the nf-spawn #55 symlink).
    // regions    : restrict variant calling to chr20 for demo speed.
    samples   = '{samples_uri}'
    reference = '{reference_uri}'
    regions   = '20'
    // bcftools image for CALL_VARIANTS's explicit `docker run` (that process is
    // NOT containerised by Nextflow — it runs aws-cli on the host, bcftools in
    // Docker). Arch-correct: aarchbio on arm64, biocontainers on x86.
    bcftools_image = '{bcftools_image}'
    // FSx mount on each task — CALL_VARIANTS reads the shared reference directly
    // from <fsx_mount>/reference (zero-copy; nf-spawn ext.fsx mounts the FS).
    fsx_mount = '{fsx_mount}'
}}

// S3 work directory — intermediate files pass between instances via S3.
// Each task downloads its inputs, runs, uploads outputs, terminates.
workDir = 's3://{bucket}/work/{job_name}/'

// Publish final results to a separate prefix (not the ephemeral work dir).
params.outdir = 's3://{bucket}/results/{job_name}/'

{container_overrides}

// Trace file written to S3 — the dashboard polls this for live progress.
trace {{
    enabled   = true
    overwrite = true
    file      = 's3://{bucket}/results/{job_name}/trace.tsv'
    fields    = 'task_id,name,status,exit,start,complete,duration,realtime,cpus,memory,rss,vmem,rchar,wchar'
}}

timeline {{
    enabled   = true
    overwrite = true
    file      = 's3://{bucket}/results/{job_name}/timeline.html'
}}

report {{
    enabled   = true
    overwrite = true
    file      = 's3://{bucket}/results/{job_name}/report.html'
}}
"""


# Native arm64 container overrides (quay.io/aarchbio). The custom main.nf runs
# bcftools (mpileup/call/merge/stats) + samtools (faidx/index); the upstream
# quay.io/biocontainers images are amd64-only and `exec format error` on
# Graviton, so each process is pinned to its native arm64 rebuild. Tags mirror
# the biocontainers <version>--<build>: aarchbio bcftools 1.23.1--h89c24a7_0 and
# samtools 1.23.1--hc7977f4_0 verified live on quay.io/aarchbio 2026-06 (same
# upstream versions as quay.io/biocontainers bcftools/samtools 1.23.1). NOTE:
# CALL_VARIANTS needs BOTH tools (samtools index/faidx + bcftools); main.nf runs
# both from this single bcftools image if it bundles samtools, OR the samtools
# step uses the samtools image below — verify against the shipped main.nf.
# The x86 leg emits the upstream amd64 biocontainers (same versions; run native).
_AARCHBIO_CONTAINER_OVERRIDES = """\
// ── Native arm64 container overrides (quay.io/aarchbio) ──────────────────────
// CALL_VARIANTS is NOT here: it runs aws-cli on the host + bcftools via explicit
// `docker run` (params.bcftools_image), so Nextflow must not wrap it in a
// container. MERGE_VCFS/VCF_STATS are pure-bcftools and run containerised.
process {
    withName: 'MERGE_VCFS' { container = 'quay.io/aarchbio/bcftools:1.23.1--h89c24a7_0' }
    withName: 'VCF_STATS'  { container = 'quay.io/aarchbio/bcftools:1.23.1--h89c24a7_0' }
}
"""

# x86 leg containers — upstream amd64 biocontainers (run native on c7i/r7i).
# Emitted so the x86 leg pins the SAME tool versions as the arm64 leg (only the
# arch differs), keeping the benchmark a clean matched comparison.
_BIOCONTAINER_CONTAINER_OVERRIDES = """\
// ── x86 biocontainer images (quay.io/biocontainers, amd64 native) ────────────
// CALL_VARIANTS not here — see arm64 note (host aws-cli + docker-run bcftools).
process {
    withName: 'MERGE_VCFS' { container = 'quay.io/biocontainers/bcftools:1.23.1--hb2cee57_0' }
    withName: 'VCF_STATS'  { container = 'quay.io/biocontainers/bcftools:1.23.1--hb2cee57_0' }
}
"""


def tools_ami(cfg) -> str:
    """The tools AMI for the configured arch (x86 → AMI_ID_X86, arm64 → AMI_ID_ARM64)."""
    if _arch(cfg) == "x86":
        return getattr(cfg, "AMI_ID_X86", "") or cfg.AMI_ID
    return getattr(cfg, "AMI_ID_ARM64", "") or cfg.AMI_ID


def render(cfg, queue_size: int) -> str:
    """Return a nextflow.config string with all values substituted.

    Architecture-parametric: cfg.BENCH_ARCH selects the instance family pairs
    (c7g/r7g vs c7i/r7i), the tools AMI, and whether the aarchbio arm64 container
    overrides are emitted (arm64) or the upstream amd64 biocontainers (x86). The
    reference-genome EBS snapshot / FSx filesystem is arch-neutral either way.

    Args:
        cfg:        config module (REGION, BUCKET, JOB_NAME, AMI_ID, VOLUME_SIZE,
                    BENCH_ARCH, AMI_ID_ARM64/AMI_ID_X86).
        queue_size: derived from truffle.derive_queue_size().
    """
    arch = _arch(cfg)
    labels = _LABEL_INSTANCE_TYPES_BY_ARCH[arch]
    ami_id_tools = tools_ami(cfg)
    container_overrides = (
        _AARCHBIO_CONTAINER_OVERRIDES if arch == "arm64" else _BIOCONTAINER_CONTAINER_OVERRIDES
    )
    # bcftools image for CALL_VARIANTS's explicit `docker run` (arch-correct).
    bcftools_image = (
        "quay.io/aarchbio/bcftools:1.23.1--h89c24a7_0"
        if arch == "arm64"
        else "quay.io/biocontainers/bcftools:1.23.1--hb2cee57_0"
    )

    # Pin every task to one AZ (nf-spawn 0.7.0 ext.az → spawn launch --az, the
    # released fix for nf-spawn#62) when cfg.BENCH_AZ is set — so volumes from
    # FSR-warmed reference snapshots are fast-restored (FSR is per-AZ; an
    # unpinned task can land in a cold AZ and lazy-load the reference from S3 at
    # ~6-8 MB/s). Empty → spawn's default placement. The trailing newline+indent
    # keeps the next ext line aligned in the rendered config.
    bench_az = getattr(cfg, "BENCH_AZ", "")
    az_line = f"ext.az           = '{bench_az}'\n        " if bench_az else ""

    # ── Reference delivery mode (precedence: FSx → EBS volume → baked AMI) ────
    # The shared read-only human reference genome (~3 GB FASTA + .fai) every
    # CALL_VARIANTS task reads. FSx for Lustre is the WIDE-FAN-OUT answer: one
    # S3-backed shared filesystem mounted read-only by every task, no per-volume
    # FSR credit limit (which caps EBS-snapshot volumes at ~10 warm concurrent —
    # see the FSR-credit finding). The reference lives once on the FS at
    # <fsx_mount>/reference; tasks read it in place.
    #
    # NOTE: nf-spawn 0.8.0 does NOT yet forward ext.fsx — filed as nf-spawn#67
    # (both the launch flag AND feeding the FSx mount into the #55 symlink path).
    # This emission is wired READY for that release; the exact ext.fsx schema
    # tracks #67 and may need a tweak when it lands. Until then FSX_ID is unset
    # and we fall back to ext.volumes (clean at small N) or the baked reference.
    fsx_id = getattr(cfg, "FSX_ID", "")
    fsx_mount = getattr(cfg, "FSX_MOUNT", "/fsx")

    def _ref_delivery_line(snapshot: str, vol_mount: str, ref_name: str) -> str:
        """The per-process ext.* line that delivers the reference read-only, or ''.

        FSx: ONE shared filesystem (fsx_id) mounted at fsx_mount on every task;
        the reference lives at fsx_mount/<ref_name>. The `paths: ['<ref_name>']`
        field is REQUIRED (nf-spawn 0.7.x #67): a shared FS roots at /fsx but the
        reference sits at /fsx/<name>, so the symlink-eligible path must be
        <mount>/<name> — without `paths`, nf-spawn only exposes the bare /fsx
        (basename 'fsx'), which won't match the 'reference' stage name and the
        staged s3:// reference marker would be copied instead of symlinked. With
        it, params.reference resolves zero-copy. EBS: a snapshot volume at
        vol_mount. Neither set → baked-AMI path.
        """
        if fsx_id:
            return f"ext.fsx     = [ id: '{fsx_id}', mount: '{fsx_mount}', paths: ['{ref_name}'] ]"
        if snapshot:
            return (
                f"ext.volumes = [[ snapshot: '{snapshot}', mount: '{vol_mount}', readOnly: true ]]"
            )
        return ""

    # Reference genome (process_medium / CALL_VARIANTS). On FSx it's
    # /fsx/reference; on EBS the snapshot mount. The basename 'reference' matches
    # the s3:// params.reference marker for the #55 symlink.
    ref_snapshot = getattr(cfg, "REFERENCE_SNAPSHOT", "")
    ref_mount = getattr(cfg, "REFERENCE_MOUNT", "/opt/reference")
    ref_delivery_line = _ref_delivery_line(ref_snapshot, ref_mount, "reference")

    # main.nf inputs: the samples CSV and the reference marker URIs live under
    # the job's input/reference prefixes (written by pipeline.write_samples_csv /
    # write_reference_marker). Fall back to the job-derived default paths.
    bucket = cfg.BUCKET
    job_name = cfg.JOB_NAME
    samples_uri = getattr(cfg, "SAMPLES_URI", f"s3://{bucket}/input/{job_name}/samples.csv")
    reference_uri = getattr(cfg, "REFERENCE_URI", f"s3://{bucket}/reference/{job_name}/reference")

    return _TEMPLATE.format(
        region=cfg.REGION,
        bucket=bucket,
        job_name=job_name,
        ami_id=cfg.AMI_ID,
        ami_id_tools=ami_id_tools,
        queue_size=queue_size,
        volume_size=getattr(cfg, "VOLUME_SIZE", 40),
        ref_delivery_line=ref_delivery_line,
        container_overrides=container_overrides,
        az_line=az_line,
        samples_uri=samples_uri,
        reference_uri=reference_uri,
        bcftools_image=bcftools_image,
        fsx_mount=getattr(cfg, "FSX_MOUNT", "/fsx"),
        inst_single=labels["process_single"],
        inst_low=labels["process_low"],
        inst_medium=labels["process_medium"],
        inst_high=labels["process_high"],
    )
